#!/bin/bash

echo "Executing stopart"
/home/art_coord_ramp_metering/system/stopart
sleep 2

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/art_coord_ramp_metering/src/lnx/clt_vars &
sleep 1

echo "Starting ab3418comm"
#/home/atsc/ab3418/lnx/ab3418comm -u & 
#/home/atsc/ab3418/lnx/ab3418comm -i 1000 -u -p /dev/ttyS0 >>/big/data/ac_rm_1/ab3418comm.out 2 >>/big/data/ac_rm_1/ab3418comm.err &
/home/atsc/ab3418/lnx/ab3418comm -i 1000 -u -p /dev/ttyUSB0 >>/big/data/ac_rm_1/ab3418comm.out 2>>/big/data/ac_rm_1/ab3418comm.err &
sleep 5

echo "Starting receive_urms_data_go.sh"
/home/art_coord_ramp_metering/system/receive_urms_data_go.sh &
sleep 1

#echo "Starting ac_rm_algo"
#cd /home/art_coord_ramp_metering/src 
#./lnx/ac_rm_algo &
#sleep 1

#echo "Starting wrfiles_ac_rm"
/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -d /big/data/ac_rm_1 -m 15 &
#/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -o
