#!/bin/bash

echo "Killing wrfiles_ac_rm"
killall wrfiles_ac_rm
sleep 1

echo "Killing ac_rm_algo"
killall ac_rm_algo
sleep 1

echo "Killing urms"
killall urms
sleep 1

echo "Killing receive_urms_data"
killall receive_urms_data
sleep 1

echo "Killing ab3418comm"
killall ab3418comm
sleep 1

echo "Killing clt_vars"
killall clt_vars
sleep 1

echo "Killing db_slv"
killall db_slv
sleep 1

echo "Executing db_clean.sh"
/home/path/db/db_clean.sh
sleep 2


echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/art_coord_ramp_metering/src/lnx/clt_vars &
sleep 1

echo "Starting ab3418comm"
#/home/atsc/ab3418/lnx/ab3418comm -u & 
/home/atsc/ab3418/lnx/ab3418comm -i 1000 -u -p /dev/ttyS0 >>/big/data/ac_rm_1/ab3418comm.out 2 >>/big/data/ac_rm_1/ab3418comm.err &
#/home/atsc/ab3418/lnx/ab3418comm -i 1000 -u -p /dev/ttyUSB0 >>/big/data/ac_rm_1/ab3418comm.out 2>>/big/data/ac_rm_1/ab3418comm.err &
sleep 5

echo "Starting receive_urms_data"
/home/atsc/ab3418/lnx/receive_urms_data -v  &
sleep 1

#echo "Starting ac_rm_algo"
#cd /home/art_coord_ramp_metering/src 
#./lnx/ac_rm_algo &
#sleep 1

#echo "Starting wrfiles_ac_rm"
/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -d /big/data/ac_rm_1 -m 15 
