#!/bin/bash

echo "Killing wrfiles_ac_rm"
killall wrfiles_ac_rm
sleep 1

echo "Killing ac_rm_algo"
killall ac_rm_algo
sleep 1

echo "Killing urms"
killall urms
sleep 1

echo "Killing receive_urms_data"
killall receive_urms_data
sleep 1

echo "Killing receive_urms_data_go.sh"
killall receive_urms_data_go.sh
sleep 1

echo "Killing clt_vars"
killall clt_vars
sleep 1

echo "Killing ab3418comm"
killall ab3418comm
sleep 1

echo "Killing db_slv"
killall db_slv
