#!/bin/bash

echo "Stopping send_urms_data"
killall send_urms_data
pid=`ps -elf | grep -v grep | grep '/bin/bash /home/art_coord_ramp_metering/system/send_urms_data_go.sh' | awk '{print $4}'`
kill $pid
sleep 1

echo "Stopping urms"
killall urms
sleep 1

echo "Stopping db_slv"
killall db_slv
sleep 1

/home/path/db/db_clean.sh
