#!/bin/bash

echo "Executing stopurms"
/home/art_coord_ramp_metering/system/stopurms
sleep 1

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/art_coord_ramp_metering/src/lnx/clt_vars &
sleep 1

if [[ ($1 == "no_control") || ($2 == "no_control") ]]
then
	echo "Starting urms with no control"
	/home/atsc/urms/lnx/urms -r 10.0.1.126 -i 100 -n &
else
	echo "Starting urms"
	/home/atsc/urms/lnx/urms -r 10.0.1.126 -i 100 >>/big/data/ac_rm_1/urms.err &
fi
sleep 1

if [[ $1 != "sj" ]]
then
	echo "Starting send_urms"
	/home/art_coord_ramp_metering/system/send_urms_data_go.sh $1 >>/big/data/ac_rm_1/send_urms_data.err &
	sleep 1
fi

if [[ $1 == "sj" ]]
then
	echo "Starting ac_rm_algo"
	cd /home/art_coord_ramp_metering/src
	./lnx/ac_rm_algo >>/big/data/ac_rm_1/ac_rm_algo.err &
	sleep 1
fi

#echo "Starting wrfiles_ac_rm"
if [[ $1 == "home" ]]
then
	/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -d /big/data/ac_rm_1 -o
else
	/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -d /big/data/ac_rm_1 -m 15 >/big/data/ac_rm_1/wrfiles_ac_rm.err &
fi
