#!/bin/bash

echo "Stopping send_urms_data"
killall send_urms_data
pid=`ps -elf | grep -v grep | grep '/bin/bash /home/art_coord_ramp_metering/system/send_urms_data_go.sh' | awk '{print $4}'`
kill $pid
sleep 1

echo "Stopping urms"
killall urms
sleep 1

echo "Stopping clt_vars"
killall clt_vars
sleep 1

echo "Stopping db_slv"
killall db_slv
sleep 1

/home/path/db/db_clean.sh

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/art_coord_ramp_metering/src/lnx/clt_vars &
sleep 1

echo "Starting urms"
/home/atsc/urms/lnx/urms -r 10.0.1.126 -i 100 &
sleep 1

echo "Starting send_urms"
/home/art_coord_ramp_metering/system/send_urms_data_go.sh -i 1000 &
sleep 1

#echo "Starting wrfiles_ac_rm"
/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -d /big/data/ac_rm_1 -m 15 &
#/home/art_coord_ramp_metering/src/lnx/wrfiles_ac_rm -d /big/data/ac_rm_1 -o
