# Makefile
# Took out build for second executable with -DCOMPARE
#
# Copyright (c) 2008   Regents of the University of California
#
include $(CAPATH_MK_DEFS)

PATH_LDFLAGS += -L./lnx
PATH_CFLAGS += -I$(ATSC_INC_DIR) -pg
#PATH_OBJS += $(OBJDIR)/signal_lib.o
PATH_OBJS += $(OBJDIR)/signal_opt.o
PATH_OBJS += $(OBJDIR)/nrutil2.o $(OBJDIR)/simplx.o

all: 	$(OBJDIR) $(PATH_OBJS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	\rm -f $(OBJDIR)/*.[oa] *.*~
